import 'package:flutter/material.dart';

enum AppLanguage { en, ne, hi, es, zh, ja }

class LocalizationService {
  static AppLanguage _currentLanguage = AppLanguage.en;

  static void setLanguage(AppLanguage lang) => _currentLanguage = lang;
  static AppLanguage get currentLanguage => _currentLanguage;

  static String translate(String key) {
    return _strings[_currentLanguage]?[key] ?? _strings[AppLanguage.en]?[key] ?? key;
  }

  static final Map<AppLanguage, Map<String, String>> _strings = {
    AppLanguage.en: {
      'app_name': 'FlirtMate',
      'choose_style': 'CHOOSE YOUR',
      'flirt_style': 'Flirt Style',
      'tagline': 'Premium lines for sophisticated connections',
      'mood_mixer': 'Mood Mixer',
      'mood_mixer_desc': 'Blend styles for a custom signature',
      'get_started': 'Get Started',
      'personalize_hint': 'Personalize with a name, detail, or vibe',
      'romantic': 'Romantic', 'romantic_desc': 'Deep, heartfelt love lines',
      'funny': 'Funny', 'funny_desc': 'Humorous & punny openers',
      'light': 'Light', 'light_desc': 'Soft, innocent compliments',
      'playful': 'Playful', 'playful_desc': 'Teasing, witty banter',
      'classy': 'Classy', 'classy_desc': 'Elegant & refined charm',
      'confident': 'Confident', 'confident_desc': 'Bold, self-assured openers',
      'shy': 'Shy', 'shy_desc': 'Cute, adorably awkward',
      'mysterious': 'Mysterious', 'mysterious_desc': 'Intriguing, dark energy',
      'spicy': 'Spicy', 'spicy_desc': 'Intense & passionate lines',
      'oldschool': 'Old-School', 'oldschool_desc': 'Classic, letter-style charm',
      'nerdy': 'Nerdy', 'nerdy_desc': 'Clever science & tech wit',
      'wholesome': 'Wholesome', 'wholesome_desc': 'Pure, kind affirmations',
      'smooth': 'Smooth', 'smooth_desc': 'Cool, Bond-style delivery',
      'poetic': 'Poetic', 'poetic_desc': 'Lyrical, beautiful verse',
    },
    AppLanguage.ne: {
      'app_name': 'FlirtMate',
      'choose_style': 'आफ्नो रोज्नुहोस्',
      'flirt_style': 'फ्लर्ट शैली',
      'tagline': 'परिष्कृत जडानका लागि प्रिमियम लाइनहरू',
      'mood_mixer': 'मुड मिक्सर',
      'mood_mixer_desc': 'अनुकूलनका लागि शैलीहरू मिलाउनुहोस्',
      'get_started': 'सुरु गरौं',
      'personalize_hint': 'नाम वा मुड अनुसार व्यक्तिगत बनाउनुहोस्',
      'romantic': 'रोमान्टिक', 'romantic_desc': 'गहिरो र हृदयस्पर्शी शब्दहरू',
      'funny': 'रमाइलो', 'funny_desc': 'हसाउने र रोचक कुराहरू',
      'light': 'हल्का', 'light_desc': 'कोमल र मीठा प्रशंसाहरू',
      'playful': 'चञ्चल', 'playful_desc': 'जिस्क्याउने र चलाख कुराहरू',
      'classy': 'शालीन', 'classy_desc': 'भव्य र परिष्कृत आकर्षण',
      'confident': 'आत्मविश्वासी', 'confident_desc': 'साहसी र स्पष्ट कुराहरू',
      'shy': 'लजालु', 'shy_desc': 'प्यारो र अलि अप्ठ्यारो मुड',
      'mysterious': 'रहस्यमय', 'mysterious_desc': 'चासो जगाउने गहिरो कुराहरू',
      'spicy': 'तातो', 'spicy_desc': 'तीव्र र भावुक अभिव्यक्ति',
      'oldschool': 'पुरानो शैली', 'oldschool_desc': 'शास्त्रीय र मौलिक आकर्षण',
      'nerdy': 'विद्वान', 'nerdy_desc': 'बुद्धिमान र प्राविधिक शैली',
      'wholesome': 'पवित्र', 'wholesome_desc': 'शुद्ध र दयालु भावनाहरू',
      'smooth': 'प्रवाह', 'smooth_desc': 'सहज र आकर्षक शैली',
      'poetic': 'काव्यात्मक', 'poetic_desc': 'लयबद्ध र सुन्दर कविता',
    },
    AppLanguage.hi: {
      'app_name': 'FlirtMate',
      'choose_style': 'अपना चुनें',
      'flirt_style': 'फ्लर्ट स्टाइल',
      'tagline': 'परिष्कृत संबंधों के लिए प्रीमियम लाइनें',
      'mood_mixer': 'मूड मिक्सर',
      'mood_mixer_desc': 'कस्टम सिग्नेचर के लिए स्टाइल मिलाएं',
      'get_started': 'शुरू करें',
      'personalize_hint': 'नाम, विवरण या वाइब के साथ व्यक्तिगत करें',
      'romantic': 'रोमांटिक', 'romantic_desc': 'गहरे और दिल को छू लेने वाले शब्द',
      'funny': 'मज़ेदार', 'funny_desc': 'हंसी और मज़ाक वाले ओपनर्स',
      'light': 'हल्का', 'light_desc': 'सौम्य और प्यारी तारीफें',
      'playful': 'चंचल', 'playful_desc': 'शरारती और चतुर बातचीत',
      'classy': 'क्लासी', 'classy_desc': 'शानदार और परिष्कृत आकर्षण',
      'confident': 'आत्मविश्वासी', 'confident_desc': 'साहसी और प्रभावशाली अंदाज़',
      'shy': 'शर्मीला', 'shy_desc': 'प्यारा और थोड़ा संकोची मुड',
      'mysterious': 'रहस्यमय', 'mysterious_desc': 'दिलचस्प और गहरा अंदाज़',
      'spicy': 'मसालेदार', 'spicy_desc': 'तीव्र और भावुक संदेश',
      'oldschool': 'पुराना अंदाज़', 'oldschool_desc': 'क्लासिक और शालीन आकर्षण',
      'nerdy': 'नर्डी', 'nerdy_desc': 'बुद्धिमान और तकनीकी मज़ाक',
      'wholesome': 'निर्मल', 'wholesome_desc': 'शुद्ध और दयालु भावनाएं',
      'smooth': 'स्मूथ', 'smooth_desc': 'सहज और प्रभावशाली बातचीत',
      'poetic': 'काव्यात्मक', 'poetic_desc': 'लयबद्ध और सुंदर शब्द',
    },
    AppLanguage.es: {
      'app_name': 'FlirtMate',
      'choose_style': 'ELIJA SU',
      'flirt_style': 'Estilo de Flirteo',
      'tagline': 'Líneas premium para conexiones sofisticadas',
      'mood_mixer': 'Mezclador de Humor',
      'mood_mixer_desc': 'Mezcla estilos para una firma personalizada',
      'get_started': 'Empezar',
      'personalize_hint': 'Personaliza con nombre, detalle o vibra',
      'romantic': 'Romántico', 'romantic_desc': 'Líneas de amor profundas',
      'funny': 'Divertido', 'funny_desc': 'Ocurrencias graciosas',
      'light': 'Ligero', 'light_desc': 'Cumplidos suaves e inocentes',
      'playful': 'Juguetón', 'playful_desc': 'Banter ingenioso y burlón',
      'classy': 'Elegante', 'classy_desc': 'Encanto refinado y sofisticado',
      'confident': 'Seguro', 'confident_desc': 'Abridores audaces y decididos',
      'shy': 'Tímido', 'shy_desc': 'Tierno y adorablemente torpe',
      'mysterious': 'Misterioso', 'mysterious_desc': 'Energía intrigante y oscura',
      'spicy': 'Picante', 'spicy_desc': 'Líneas intensas y apasionadas',
      'oldschool': 'Clásico', 'oldschool_desc': 'Encanto de carta antigua',
      'nerdy': 'Friki', 'nerdy_desc': 'Ingenio científico y técnico',
      'wholesome': 'Sano', 'wholesome_desc': 'Afirmaciones puras y amables',
      'smooth': 'Suave', 'smooth_desc': 'Entrega genial estilo Bond',
      'poetic': 'Poético', 'poetic_desc': 'Versos líricos y bellos',
    },
    AppLanguage.zh: {
      'app_name': 'FlirtMate',
      'choose_style': '选择你的',
      'flirt_style': '搭讪风格',
      'tagline': '为高端社交打造的优质话术',
      'mood_mixer': '心情混音器',
      'mood_mixer_desc': '混合风格，打造专属签名',
      'get_started': '开始体验',
      'personalize_hint': '使用名称、细节或氛围进行个性化设置',
      'romantic': '浪漫', 'romantic_desc': '深情且动人心弦的话语',
      'funny': '幽默', 'funny_desc': '风趣幽默的开场白',
      'light': '清新', 'light_desc': '温柔纯真的甜美赞美',
      'playful': '俏皮', 'playful_desc': '调皮机智的互动',
      'classy': '高级', 'classy_desc': '优雅大方的绅士魅力',
      'confident': '自信', 'confident_desc': '大胆自信的开场',
      'shy': '含蓄', 'shy_desc': '呆萌可爱的小羞涩',
      'mysterious': '神秘', 'mysterious_desc': '耐人寻味的神秘气息',
      'spicy': '火辣', 'spicy_desc': '热烈奔放的激情话语',
      'oldschool': '怀旧', 'oldschool_desc': '经典的情书式浪漫',
      'nerdy': '极客', 'nerdy_desc': '聪明的科学与技术梗',
      'wholesome': '治愈', 'wholesome_desc': '纯粹友善的正能量',
      'smooth': '圆滑', 'smooth_desc': '冷静从容的邦德式风格',
      'poetic': '诗意', 'poetic_desc': '如诗如画的美丽辞藻',
    },
    AppLanguage.ja: {
      'app_name': 'FlirtMate',
      'choose_style': 'スタイルを選択',
      'flirt_style': 'フリルのスタイル',
      'tagline': '洗練されたつながりのためのプレミアムな一言',
      'mood_mixer': 'ムードミキサー',
      'mood_mixer_desc': 'スタイルを組み合わせて自分らしく',
      'get_started': 'はじめる',
      'personalize_hint': '名前や雰囲気でパーソナライズ',
      'romantic': 'ロマンチック', 'romantic_desc': '心温まる深い愛の言葉',
      'funny': '面白い', 'funny_desc': 'ユーモア溢れる開場白',
      'light': 'ライト', 'light_desc': '優しく純粋な褒め言葉',
      'playful': '遊び心', 'playful_desc': '茶目っ気たっぷりの会話',
      'classy': '上品', 'classy_desc': '洗練されたエレガントな魅力',
      'confident': '自信', 'confident_desc': '堂々とした力強い言葉',
      'shy': 'シャイ', 'shy_desc': '可愛らしく控えめな表現',
      'mysterious': 'ミステリアス', 'mysterious_desc': '興味をそそる神秘的な響き',
      'spicy': 'スパイシー', 'spicy_desc': '情熱的で刺激的な一言',
      'oldschool': 'レトロ', 'oldschool_desc': '古き良きラブレターの魅力',
      'nerdy': '知性的', 'nerdy_desc': '賢くてテクニカルなジョーク',
      'wholesome': 'ピュア', 'wholesome_desc': '純粋で優しい肯定感',
      'smooth': 'スムーズ', 'smooth_desc': 'スマートで格好いい語り口',
      'poetic': 'ポエティック', 'poetic_desc': '詩的で美しいフレーズ',
    },
  };
}
