enum AppLanguage { en, ne, hi, es, zh, ja }

class LocalizationService {
  static AppLanguage _currentLanguage = AppLanguage.en;

  static void setLanguage(AppLanguage lang) => _currentLanguage = lang;
  static AppLanguage get currentLanguage => _currentLanguage;

  static String translate(String key) {
    return _strings[_currentLanguage]?[key] ?? _strings[AppLanguage.en]?[key] ?? key;
  }

  static final Map<AppLanguage, Map<String, String>> _strings = {
    AppLanguage.en: {
      'app_name': 'FlirtMate',
      'choose_style': 'CHOOSE YOUR',
      'flirt_style': 'Flirt Style',
      'tagline': 'Premium lines for sophisticated connections',
      'mood_mixer': 'Mood Mixer',
      'mood_mixer_desc': 'Blend styles for a custom signature',
      'get_started': 'Get Started',
      'personalize_hint': 'Personalize with a name, detail, or vibe',
      'for': 'For', 'about': 'About',
      'stage_opener': 'Opener', 'stage_followUp': 'Follow-up', 'stage_deeper': 'Deeper',
      'romantic': 'Romantic', 'romantic_desc': 'Deep, heartfelt love lines', 'romantic_tagline': 'Touch the heart',
      'funny': 'Funny', 'funny_desc': 'Humorous & punny openers', 'funny_tagline': 'Make them laugh',
      'light': 'Light', 'light_desc': 'Soft, innocent compliments', 'light_tagline': 'Keep it sweet',
      'playful': 'Playful', 'playful_desc': 'Teasing, witty banter', 'playful_tagline': 'Fun & teasing',
      'classy': 'Classy', 'classy_desc': 'Elegant & refined charm', 'classy_tagline': 'Effortless elegance',
      'confident': 'Confident', 'confident_desc': 'Bold, self-assured openers', 'confident_tagline': 'Own the room',
      'shy': 'Shy', 'shy_desc': 'Cute, adorably awkward', 'shy_tagline': 'Adorably real',
      'mysterious': 'Mysterious', 'mysterious_desc': 'Intriguing, dark energy', 'mysterious_tagline': 'Leave them curious',
      'spicy': 'Spicy', 'spicy_desc': 'Intense & passionate lines', 'spicy_tagline': 'Turn up the heat',
      'oldschool': 'Old-School', 'oldschool_desc': 'Classic, letter-style charm', 'oldschool_tagline': 'Timeless romance',
      'nerdy': 'Nerdy', 'nerdy_desc': 'Clever science & tech wit', 'nerdy_tagline': 'Geek is chic',
      'wholesome': 'Wholesome', 'wholesome_desc': 'Pure, kind affirmations', 'wholesome_tagline': 'Warm the soul',
      'smooth': 'Smooth', 'smooth_desc': 'Cool, Bond-style delivery', 'smooth_tagline': 'Ice cold delivery',
      'poetic': 'Poetic', 'poetic_desc': 'Lyrical, beautiful verse', 'poetic_tagline': 'Pure artistry',
      'new_line': 'NEW LINE', 'save': 'SAVE', 'saved': 'SAVED', 'copy': 'COPY', 'share': 'SHARE',
      'favorites': 'Favorites', 'no_favorites': 'No favorites yet',
      'mix_generate': 'Mix & Generate', 'pick_2': 'Pick any 2 styles to blend together',
      'tagline_splash': 'Say it better. Say it right.',
      'generating': 'Generating...', 'crafting': 'CRAFTING...',
      'added_to_fav': 'Added to favorites', 'removed_from_fav': 'Removed from favorites',
      'copied': 'Copied to clipboard', 'error_title': 'Something went wrong',
      'tap_to_retry': 'Tap to retry', 'tap_begin': 'TAP "NEW LINE" TO BEGIN',
      'picked': 'Picked', 'choose_more': 'choose one more', 'ready_mix': 'ready to mix', 'pick_2_short': 'Pick 2 styles',
    },
    AppLanguage.ne: {
      'app_name': 'FlirtMate',
      'choose_style': 'आफ्नो रोज्नुहोस्',
      'flirt_style': 'फ्लर्ट शैली',
      'tagline': 'परिष्कृत जडानका लागि प्रिमियम लाइनहरू',
      'mood_mixer': 'मुड मिक्सर',
      'mood_mixer_desc': 'अनुकूलनका लागि शैलीहरू मिलाउनुहोस्',
      'get_started': 'सुरु गरौं',
      'personalize_hint': 'नाम वा मुड अनुसार व्यक्तिगत बनाउनुहोस्',
      'for': 'का लागि', 'about': 'बारेमा',
      'stage_opener': 'ओपनर', 'stage_followUp': 'फलो-अप', 'stage_deeper': 'गहिरो',
      'romantic': 'रोमान्टिक', 'romantic_desc': 'गहिरो र हृदयस्पर्शी शब्दहरू', 'romantic_tagline': 'मन छुनुहोस्',
      'funny': 'रमाइलो', 'funny_desc': 'हसाउने र रोचक कुराहरू', 'funny_tagline': 'हँसाउनुहोस्',
      'light': 'हल्का', 'light_desc': 'कोमल र मीठा प्रशंसाहरू', 'light_tagline': 'मीठो राख्नुहोस्',
      'playful': 'चञ्चल', 'playful_desc': 'जिस्क्याउने र चलाख कुराहरू', 'playful_tagline': 'रमाइलो र जिस्क्याउने',
      'classy': 'शालीन', 'classy_desc': 'भव्य र परिष्कृत आकर्षण', 'classy_tagline': 'सहज भव्यता',
      'confident': 'आत्मविश्वासी', 'confident_desc': 'साहसी र स्पष्ट कुराहरू', 'confident_tagline': 'प्रभाव जमाउनुहोस्',
      'shy': 'लजालु', 'shy_desc': 'प्यारो र अलि अप्ठ्यारो मुड', 'shy_tagline': 'वास्तविक र प्यारो',
      'mysterious': 'रहस्यमय', 'mysterious_desc': 'चासो जगाउने गहिरो कुराहरू', 'mysterious_tagline': 'जिज्ञासु छोड्नुहोस्',
      'spicy': 'तातो', 'spicy_desc': 'तीव्र र भावुक अभिव्यक्ति', 'spicy_tagline': 'गर्मी बढाउनुहोस्',
      'oldschool': 'पुरानो शैली', 'oldschool_desc': 'शास्त्रीय र मौलिक आकर्षण', 'oldschool_tagline': 'कालातीत रोमान्स',
      'nerdy': 'विद्वान', 'nerdy_desc': 'बुद्धिमान र प्राविधिक शैली', 'nerdy_tagline': 'गीक चतुर छ',
      'wholesome': 'पवित्र', 'wholesome_desc': 'शुद्ध र दयालु भावनाहरू', 'wholesome_tagline': 'आत्मा न्यानो बनाउनुहोस्',
      'smooth': 'प्रवाह', 'smooth_desc': 'सहज र आकर्षक शैली', 'smooth_tagline': 'सहज प्रस्तुति',
      'poetic': 'काव्यात्मक', 'poetic_desc': 'लयबद्ध र सुन्दर कविता', 'poetic_tagline': 'शुद्ध कला',
      'new_line': 'नयाँ हरफ', 'save': 'बचत गर्नुहोस्', 'saved': 'बचत गरियो', 'copy': 'प्रतिलिपि', 'share': 'साझा गर्नुहोस्',
      'favorites': 'मनपर्ने', 'no_favorites': 'अहिलेसम्म कुनै मनपर्ने छैन',
      'mix_generate': 'मिश्रण र सिर्जना', 'pick_2': 'मिस्रण गर्न कुनै २ शैलीहरू छान्नुहोस्',
      'tagline_splash': 'अझ राम्रो भन्नुहोस्। सही भन्नुहोस्।',
      'generating': 'सिर्जना गर्दै...', 'crafting': 'बनाउँदै...',
      'added_to_fav': 'मनपर्नेमा थपियो', 'removed_from_fav': 'मनपर्नेबाट हटाइयो',
      'copied': 'क्लिपबोर्डमा प्रतिलिपि गरियो', 'error_title': 'केही गलत भयो',
      'tap_to_retry': 'पुनः प्रयास गर्न ट्याप गर्नुहोस्', 'tap_begin': 'सुरु गर्न "नयाँ हरफ" मा ट्याप गर्नुहोस्',
      'picked': 'छानिएको', 'choose_more': 'थप एउटा छान्नुहोस्', 'ready_mix': 'मिश्रण गर्न तयार', 'pick_2_short': '२ शैलीहरू छान्नुहोस्',
    },
    // Hindi
    AppLanguage.hi: {
      'app_name': 'FlirtMate',
      'choose_style': 'अपना चुनें',
      'flirt_style': 'फ्लर्ट स्टाइल',
      'tagline': 'परिष्कृत संबंधों के लिए प्रीमियम लाइनें',
      'mood_mixer': 'मूड मिक्सर',
      'mood_mixer_desc': 'कस्टम सिग्नेचर के लिए स्टाइल मिलाएं',
      'get_started': 'शुरू करें',
      'personalize_hint': 'नाम, विवरण या वाइब के साथ व्यक्तिगत करें',
      'for': 'के लिए', 'about': 'बारे में',
      'stage_opener': 'ओपनर', 'stage_followUp': 'फॉलो-अप', 'stage_deeper': 'गहरा',
      'romantic': 'रोमांटिक', 'romantic_desc': 'गहरे और दिल को छू लेने वाले शब्द', 'romantic_tagline': 'दिल को छुएं',
      'funny': 'मज़ेदार', 'funny_desc': 'हंसी और मज़ाक वाले ओपनर्स', 'funny_tagline': 'हंसाएं',
      'light': 'हल्का', 'light_desc': 'सौम्य और प्यारी तारीफें', 'light_tagline': 'प्यारा रखें',
      'playful': 'चंचल', 'playful_desc': 'शरारती और चतुर बातचीत', 'playful_tagline': 'मस्ती और छेड़खानी',
      'classy': 'क्लासी', 'classy_desc': 'शानदार और परिष्कृत आकर्षण', 'classy_tagline': 'सहज शालीनता',
      'confident': 'आत्मविश्वासी', 'confident_desc': 'साहसी और प्रभावशाली अंदाज़', 'confident_tagline': 'छा जाएं',
      'shy': 'शर्मीला', 'shy_desc': 'प्यारा और थोड़ा संकोची मुड', 'shy_tagline': 'प्यारा और असली',
      'mysterious': 'रहस्यमय', 'mysterious_desc': 'दिलचस्प and गहरा अंदाज़', 'mysterious_tagline': 'उत्सुकता छोड़ें',
      'spicy': 'मसालेदार', 'spicy_desc': 'तीव्र और भावुक संदेश', 'spicy_tagline': 'गर्मी बढ़ाएं',
      'oldschool': 'पुराना अंदाज़', 'oldschool_desc': 'क्लासिक और शालीन आकर्षण', 'oldschool_tagline': 'सदाबहार रोमांस',
      'nerdy': 'नर्डी', 'nerdy_desc': 'बुद्धिमान और तकनीकी मज़ाक', 'nerdy_tagline': 'गीक ठाठ है',
      'wholesome': 'निर्मल', 'wholesome_desc': 'शुद्ध और दयालु भावनाएं', 'wholesome_tagline': 'आत्मा को सुकून दें',
      'smooth': 'स्मूथ', 'smooth_desc': 'सहज और प्रभावशाली बातचीत', 'smooth_tagline': 'सहज अंदाज़',
      'poetic': 'काव्यात्मक', 'poetic_desc': 'लयबद्ध और सुंदर शब्द', 'poetic_tagline': 'शुद्ध कलात्मकता',
      'new_line': 'नई लाइन', 'save': 'सहेजें', 'saved': 'सहेजा गया', 'copy': 'कॉपी', 'share': 'साझा करें',
      'favorites': 'पसंदीदा', 'no_favorites': 'अभी तक कोई पसंदीदा नहीं',
      'mix_generate': 'मिक्स और जनरेट', 'pick_2': 'मिलाने के लिए कोई भी 2 स्टाइल चुनें',
      'tagline_splash': 'बेहतर कहें। सही कहें।',
      'generating': 'बना रहा है...', 'crafting': 'तैयार कर रहा है...',
      'added_to_fav': 'पसंदीदा में जोड़ा गया', 'removed_from_fav': 'पसंदीदा से हटाया गया',
      'copied': 'क्लिपबोर्ड पर कॉपी किया गया', 'error_title': 'कुछ गलत हो गया',
      'tap_to_retry': 'पुनः प्रयास करने के लिए टैप करें', 'tap_begin': 'शुरू करने के लिए "नई लाइन" पर टैप करें',
      'picked': 'चुना गया', 'choose_more': 'एक और चुनें', 'ready_mix': 'मिक्स करने के लिए तैयार', 'pick_2_short': '2 स्टाइल चुनें',
    },
    // Spanish
    AppLanguage.es: {
      'app_name': 'FlirtMate',
      'choose_style': 'ELIGE TU',
      'flirt_style': 'Estilo de Flirteo',
      'tagline': 'Frases premium para conexiones sofisticadas',
      'mood_mixer': 'Mezclador de Humor',
      'mood_mixer_desc': 'Mezcla estilos para una firma personalizada',
      'get_started': 'Empezar',
      'personalize_hint': 'Personaliza con nombre, detalle o vibra',
      'for': 'Para', 'about': 'Sobre',
      'stage_opener': 'Abridor', 'stage_followUp': 'Seguimiento', 'stage_deeper': 'Más profundo',
      'romantic': 'Romántico', 'romantic_desc': 'Líneas de amor profundas y sentidas', 'romantic_tagline': 'Toca el corazón',
      'funny': 'Divertido', 'funny_desc': 'Abridores humorísticos e ingeniosos', 'funny_tagline': 'Hazlos reír',
      'light': 'Ligero', 'light_desc': 'Cumplidos suaves e inocentes', 'light_tagline': 'Mantenlo dulce',
      'playful': 'Juguetón', 'playful_desc': 'Banter ingenioso y burlón', 'playful_tagline': 'Diversión y bromas',
      'classy': 'Elegante', 'classy_desc': 'Encanto refinado y sofisticado', 'classy_tagline': 'Elegancia natural',
      'confident': 'Seguro', 'confident_desc': 'Abridores audaces y decididos', 'confident_tagline': 'Domina la escena',
      'shy': 'Tímido', 'shy_desc': 'Tierno y adorablemente torpe', 'shy_tagline': 'Adorablemente real',
      'mysterious': 'Misterioso', 'mysterious_desc': 'Energía intrigante y oscura', 'mysterious_tagline': 'Déjalos curiosos',
      'spicy': 'Picante', 'spicy_desc': 'Líneas intensas y apasionadas', 'spicy_tagline': 'Sube la temperatura',
      'oldschool': 'Clásico', 'oldschool_desc': 'Encanto de carta antigua', 'oldschool_tagline': 'Romance eterno',
      'nerdy': 'Friki', 'nerdy_desc': 'Ingenio científico y técnico', 'nerdy_tagline': 'Lo geek es chic',
      'wholesome': 'Sano', 'wholesome_desc': 'Afirmaciones puras y amables', 'wholesome_tagline': 'Cura el alma',
      'smooth': 'Suave', 'smooth_desc': 'Entrega genial estilo Bond', 'smooth_tagline': 'Entrega impecable',
      'poetic': 'Poético', 'poetic_desc': 'Versos líricos y bellos', 'poetic_tagline': 'Arte puro',
      'new_line': 'NUEVA FRASE', 'save': 'GUARDAR', 'saved': 'GUARDADO', 'copy': 'COPIAR', 'share': 'COMPARTIR',
      'favorites': 'Favoritos', 'no_favorites': 'Aún no hay favoritos',
      'mix_generate': 'Mezclar y Generar', 'pick_2': 'Elige 2 estilos para mezclar',
      'tagline_splash': 'Dilo mejor. Dilo bien.',
      'generating': 'Generando...', 'crafting': 'CREANDO...',
      'added_to_fav': 'Añadido a favoritos', 'removed_from_fav': 'Eliminado de favoritos',
      'copied': 'Copiado al portapapeles', 'error_title': 'Algo salió mal',
      'tap_to_retry': 'Toca para reintentar', 'tap_begin': 'TOCA "NUEVA FRASE" PARA EMPEZAR',
      'picked': 'Elegido', 'choose_more': 'elige uno más', 'ready_mix': 'listo para mezclar', 'pick_2_short': 'Elige 2 estilos',
    },
    // Chinese
    AppLanguage.zh: {
      'app_name': 'FlirtMate',
      'choose_style': '选择你的',
      'flirt_style': '搭讪风格',
      'tagline': '为高端社交打造的优质话术',
      'mood_mixer': '心情混音器',
      'mood_mixer_desc': '混合风格，打造专属签名',
      'get_started': '开始体验',
      'personalize_hint': '使用名称、细节或氛围进行个性化设置',
      'for': '给', 'about': '关于',
      'stage_opener': '开场白', 'stage_followUp': '后续跟进', 'stage_deeper': '深入交流',
      'romantic': '浪漫', 'romantic_desc': '深情且动人心弦的话语', 'romantic_tagline': '触动心灵',
      'funny': '幽默', 'funny_desc': '风趣幽默的开场白', 'funny_tagline': '让他们开怀大笑',
      'light': '清新', 'light_desc': '温柔纯真的甜美赞美', 'light_tagline': '保持甜蜜',
      'playful': '俏皮', 'playful_desc': '调皮机智的互动', 'playful_tagline': '趣味十足',
      'classy': '高级', 'classy_desc': '优雅大方的绅士魅力', 'classy_tagline': '从容优雅',
      'confident': '自信', 'confident_desc': '大胆自信的开场', 'confident_tagline': '掌控全场',
      'shy': '含蓄', 'shy_desc': '呆萌可爱的小羞涩', 'shy_tagline': '真实可爱',
      'mysterious': '神秘', 'mysterious_desc': '耐人寻味的神秘气息', 'mysterious_tagline': '留有悬念',
      'spicy': '火辣', 'spicy_desc': '热烈奔放的激情话语', 'spicy_tagline': '升温感情',
      'oldschool': '怀旧', 'oldschool_desc': '经典的情书式浪漫', 'oldschool_tagline': '永恒的浪漫',
      'nerdy': '极客', 'nerdy_desc': '聪明的科学与技术梗', 'nerdy_tagline': '极客也时尚',
      'wholesome': '治愈', 'wholesome_desc': '纯粹友善的正能量', 'wholesome_tagline': '温暖灵魂',
      'smooth': '圆滑', 'smooth_desc': '冷静从容的邦德式风格', 'smooth_tagline': '行云流水',
      'poetic': '诗意', 'poetic_desc': '如诗如画的美丽辞藻', 'poetic_tagline': '纯粹艺术',
      'new_line': '获取新话术', 'save': '保存', 'saved': '已保存', 'copy': '复制', 'share': '分享',
      'favorites': '收藏夹', 'no_favorites': '暂无收藏',
      'mix_generate': '混合并生成', 'pick_2': '选择任意 2 种风格进行混合',
      'tagline_splash': '说得更好。说得更准。',
      'generating': '生成中...', 'crafting': '精心构思中...',
      'added_to_fav': '已添加到收藏夹', 'removed_from_fav': '已从收藏夹移除',
      'copied': '已复制到剪贴板', 'error_title': '出错了',
      'tap_to_retry': '点击重试', 'tap_begin': '点击“获取新话术”开始',
      'picked': '已选', 'choose_more': '再选一个', 'ready_mix': '准备好混合', 'pick_2_short': '选择2种风格',
    },
    // Japanese
    AppLanguage.ja: {
      'app_name': 'FlirtMate',
      'choose_style': 'スタイルを選択',
      'flirt_style': 'フリルのスタイル',
      'tagline': '洗練されたつながりのためのプレミアムな一言',
      'mood_mixer': 'ムードミキサー',
      'mood_mixer_desc': 'スタイルを組み合わせて自分らしく',
      'get_started': 'はじめる',
      'personalize_hint': '名前や雰囲気でパーソナライズ',
      'for': '宛', 'about': 'について',
      'stage_opener': 'きっかけ', 'stage_followUp': 'フォローアップ', 'stage_deeper': '深める',
      'romantic': 'ロマンチック', 'romantic_desc': '心温まる深い愛の言葉', 'romantic_tagline': '心に響く',
      'funny': '面白い', 'funny_desc': 'ユーモア溢れる開場白', 'funny_tagline': '笑わせる',
      'light': 'ライト', 'light_desc': '優しく純粋な褒め言葉', 'light_tagline': '甘く優しく',
      'playful': '遊び心', 'playful_desc': '茶目っ気たっぷりの会話', 'playful_tagline': '楽しくいたずら',
      'classy': '上品', 'classy_desc': '洗練されたエレガントな魅力', 'classy_tagline': 'さりげない気品',
      'confident': '自信', 'confident_desc': '堂々とした力強い言葉', 'confident_tagline': '主役になる',
      'shy': 'シャイ', 'shy_desc': '可愛らしく控えめな表現', 'shy_tagline': '素直で可愛い',
      'mysterious': 'ミステリアス', 'mysterious_desc': '興味をそそる神秘的な響き', 'mysterious_tagline': '好奇心をそそる',
      'spicy': 'スパイシー', 'spicy_desc': '情熱的で刺激的な一言', 'spicy_tagline': '情熱を灯す',
      'oldschool': 'レトロ', 'oldschool_desc': '古き良きラブレターの魅力', 'oldschool_tagline': '永遠の愛',
      'nerdy': '知性的', 'nerdy_desc': '賢くてテクニカルなジョーク', 'nerdy_tagline': 'ギークはクール',
      'wholesome': 'ピュア', 'wholesome_desc': '純粋で優しい肯定感', 'wholesome_tagline': '魂を癒やす',
      'smooth': 'スムーズ', 'smooth_desc': 'スマートで格好いい語り口', 'smooth_tagline': '流麗な語り',
      'poetic': 'ポエティック', 'poetic_desc': '詩的で美しいフレーズ', 'poetic_tagline': '純粋な芸術',
      'new_line': '新しい一言', 'save': '保存', 'saved': '保存済み', 'copy': 'コピー', 'share': '共有',
      'favorites': 'お気に入り', 'no_favorites': 'お気に入りはまだありません',
      'mix_generate': 'ミックスして生成', 'pick_2': 'ミックスする2つのスタイルを選択',
      'tagline_splash': 'もっと素敵に。もっと正確に。',
      'generating': '生成中...', 'crafting': '考案中...',
      'added_to_fav': 'お気に入りに追加しました', 'removed_from_fav': 'お気に入りから削除しました',
      'copied': 'クリップボードにコピーしました', 'error_title': 'エラーが発生しました',
      'tap_to_retry': 'タップして再試行', 'tap_begin': '「新しい一言」をタップして開始',
      'picked': '選択済み', 'choose_more': 'あと1つ選択してください', 'ready_mix': 'ミックスの準備完了', 'pick_2_short': '2つ選択',
    },
  };
}
